version: 2
updates:

  - package-ecosystem: "github-actions"
    commit-message:
      include: "scope"
      prefix: "Actions"
    directory: "/"
    labels:
      - "enhancement"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    commit-message:
      include: "scope"
      prefix: "requirements"
    directory: "/"
    labels:
      - "dependencies"
      - "enhancement"
    schedule:
      interval: "daily"
